### PR TITLE
Fixed pipeline build with a collection name being a prefix of the other.

### LINKED ISSUE #19: Relation between two collections sharing the same prefix generate incorrect $lookup
### Reproduction
Create a relation between two collections that share the same first part of the name - in this case `reservations`:
```ts
const relations = parseOrderedRelations([
  'reservations._id -> reservationsChanges.docId'
]);
```

### Expected output
The following `$lookup` should be generated by sparrow:
```ts
$lookup: {
  as: '$SPARROW_JOINED_reservationsChanges',
  foreignField: 'docId',
  from: 'reservationsChanges',
  localField: '_id'
}
```

### Current output
This is the current `$lookup` output generated by sparrow instead:
```ts
$lookup: {
  as: 'Changes',
  foreignField: 'docId',
  from: 'reservationsChanges',
  localField: '_id'
}
```

Which makes further computes and relations not work

### Temporary workaround
Use aliases to change the foreign collection's name like this:
```ts
const relations = parseOrderedRelations([
  'reservations._id -> ReservationsChanges.docId'
]);

const pipeline = build({
    aliases: {
      ReservationsChanges: 'reservationsChanges'
    },
    // rest of pipeline
  });
```

### PR DESCRIPTION
**Pull request by wadamek65**
Also in this PR:
- Fixed limit test name being incorrect and improved it's logic to actually test the `limit` feature.
- `testWithNCollections` function's first argument can now be an array of strings to generate collections with a fixed name or a number.
- Updated `package-lock.json` in `sparrowql-graphql` package.

### CODE REVIEW

File: __mongo__/environment.js [hunk 1]
```diff
@@ -9,9 +9,11 @@ class MongoEnvironment extends NodeEnvironment {
...
         await super.setup();
 
-        this.global.testWithNCollections = (n, name, fn) => {
-            this.global.test(name, async () => {
-                const collections = Array.from({length: n}, () => global.__MONGO__.db.collection(uuid()));
+        this.global.testWithNCollections = (newCollections, testName, fn) => {
+            this.global.test(testName, async () => {
+                const collections = Array.from({length: newCollections.length || newCollections}, (_, index) =>
+                    global.__MONGO__.db.collection(newCollections[index] || uuid())
+                );
```
Comment (radekmie) [inline __mongo__/environment.js]: Using `Array.isArray(newCollections) ? ... : ...` will make it much easier while adding TypeScript.

File: packages/sparrowql/lib/utils.js [hunk 2]
```diff
@@ -63,7 +63,7 @@ function getNameRelative(prefix, name, isPath) {
             .split('.')
             .slice(1)
             .join('.');
-    } else if (name.startsWith(prefix)) {
+    } else if (!isRelation && name.startsWith(prefix)) {
```
Comment (radekmie) [inline packages/sparrowql/lib/utils.js]: I think ``name.startsWith(`${prefix}.`)`` would be better. `getNameRelative` is only used with Mongo paths, and adding a new parameter adds unnecessary complexity.

**Review by radekmie — CHANGES_REQUESTED** [review]
It's great that you've fixed the test for `limit`, but in order to ease the maintenance, please keep PRs focused.

File: packages/sparrowql/lib/utils.js (hunk 2 above)
Comment (wadamek65) [reply packages/sparrowql/lib/utils.js]: Are you sure this is a good solution? AFAIK collection names can include dots and this bug would still be present in some edge cases.

Comment (radekmie) [reply packages/sparrowql/lib/utils.js]: Well, yes and no. Technically yes, a collection name can include dots, but SparrowQL doesn't work with such names anyway, due to the way how the rest is implemented. I'd go with that here and implement the handling of dots in names separately.

Comment (wadamek65) [reply packages/sparrowql/lib/utils.js]: I'm not sure I like your suggestion though as not only it makes this PR incomplete because there technically are still edge cases left and leaves these cases still to be fixed and requires introducing more logic. 

What I was debating though was exporting part of this logic that only applies to the collection names to a separate functions and reuse it in `getNameRelative` and `$lookup` and `$unwind` parts of the code but I was unsure on which logic should be exported.

Comment (radekmie) [reply packages/sparrowql/lib/utils.js]: I didn't want to get into this now, but OK. So using dots in collection names will break everything, because:
* We're using these names in `$group` stage for joined collections, and `{$group: {'a.b': ...}}` is invalid.
* Similarly, `$project` would create unnecessarily nested paths. While It should work most of the time, it may cause problems with arrays.

These two are from the top of my head, but I think there'll be more. That's why I think we should skip it now and get back to proper support later. Probably replacing dots with something else here and there should be enough.

Comment (wadamek65) [reply packages/sparrowql/lib/utils.js]: I just tried your suggested solution and unfortunately it breaks almost all the tests.

What I thought would be the best solution for this problem is to extract some of the logic to a separate function because it makes more sense - field paths and collection names should be treated differently and should not share the same logic. But I was unsure which logic is required by what.

File: __mongo__/environment.js (hunk 1 above)
Comment (wadamek65) [reply __mongo__/environment.js]:
```ts
                const isArray = Array.isArray(newCollections);
                const collections = Array.from({length: isArray ? newCollections.length : newCollections}, (_, index) =>
                    global.__MONGO__.db.collection(isArray ? newCollections[index] : uuid())
                );
```

Does this look ok or do you have a better idea?

Comment (radekmie) [reply __mongo__/environment.js]: This is still not OK for TypeScript, as `isArray: boolean`, not `isArray: assert Array.isArray(newCollections)`. I suggest something like this:

```ts
const db = global.__MONGO__.db;
const collections =
  Array.isArray(newCollections)
    ? newCollections.map(name => db.collection(name))
    ? Array.from({ length: newCollections }, () => db.collection(uuid()));
```

Comment (wadamek65) [reply __mongo__/environment.js]: Yeah that's what I was also thinking but wasn't sure whether or not `Array.isArray` was a typeguard by itself. Changed.

File: packages/sparrowql/lib/utils.js (hunk 2 above)
Comment (wadamek65) [reply packages/sparrowql/lib/utils.js]: After discussion we came up with a new solution by adding a dot if it was not present. Changed.

**Review by radekmie — APPROVED** [review]
